name = "jsonhero-io"
type = "javascript"
compatibility_date = "2022-02-01"

account_id = "5d7b32945c76c32f7b670624dc216fb8"
workers_dev = true

kv_namespaces = [ 
  { binding = "DOCUMENTS", id = "b3be0547a0b44e16951ea6edfc5cb389",  preview_id = "908b368b33d94c78969ffdc57623d3f4" }
]


main = "dist/worker.js"

[vars]
GRAPH_JSON_COLLECTION = "jsonhero-dev"

[site]
bucket = "./public"



[build]
command = "npm run build:worker"
watch_dir = "build/index.js"



[env.production]
route = "json-parser.meeshoapi.workers.dev/*"
zone_id = "af3c12add61e94b88b3d2cbfb6f65782"
kv_namespaces = [ 
  { binding = "DOCUMENTS", id = "e517c369774a443eba95afff9128f7b6" }
]

[env.production.vars]
GRAPH_JSON_COLLECTION = "jsonhero-prod"

# Secrets
# [SESSION_STORAGE]
# [GRAPH_JSON_API_KEY]
# [APIHERO_PROJECT_KEY]
